### ISSUE TITLE
Monolithic storage tree requires symlinking in many cases

### ISSUE THREAD

**Issue by mih** [christian-monch/dump-things-server#69]
ATM the server expects a single root directory that contains a monolithic layout. 

This is very strict, and it is also more or less incompatible with a separation of individual record collections into a set of repositories that delineate access permission types.

Each of these repos would need to be somewhat self-explanatory and host more than just the records (example: https://hub.psychoinformatics.de/inm7/knowledge). Hence they cannot be simply assembled into this required layout.

Instead, a symlink farm *must* be used (or an untracked copy collection). This in turn implies that it only runs on filesystems with symlink capabilities.

Following the model of https://github.com/christian-monch/dump-things-server/issues/67#issuecomment-2837611922 --  using a configuration file -- would allow for much more flexible setup.

Such a config file would have a `collections` section that declares the location for each collections `curated` and `incoming` zones on the file system. Extending the example from https://github.com/christian-monch/dump-things-server/issues/67#issuecomment-2837611922

```yaml
collections:
  collections_1:
    curated: /path1
    incoming: /path2
  ...
tokens:
  token_1:
    collection_1:
      mode: <mode-label>
      incoming: <staging-area-label>
    collection_2:
      ...
  token_2:
    ...
```
